name: Deploy to Production EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Check Out Repository
        uses: actions/checkout@v3

      # Passo 2: Fazer deploy dos arquivos para a EC2
      - name: Deploy Files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRODUCTION_SSH_PRIVATE_KEY}}
          ARGS: "-avzr --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.PRODUCTION_REMOTE_HOST}}
          REMOTE_USER: ${{secrets.PRODUCTION_REMOTE_USER}}
          TARGET: /projetos
          EXCLUDE: ".github/, .env"

      # Passo 3: Executar comandos no servidor remoto
      # sudo systemctl stop HoustonSmarTravel
      # npm install
      # npx prisma generate
      # npm run build
      # sudo systemctl start HoustonSmarTravel
      - name: Run Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.PRODUCTION_REMOTE_HOST}}
          username: ${{secrets.PRODUCTION_REMOTE_USER}}
          key: ${{secrets.PRODUCTION_SSH_PRIVATE_KEY}}
          script: |
            cd /projetos
            ls
            